
-- GEOESCRITORIO VIRTUAL V 4.0 BETA
-- CAPA I BASE DE DATOS DE DESARROLLO
-- DATOS DE LAS TABLAS EN EL ESQUEMA DE ADMINISTRACION "ADM"
-- AUTOR. GONZALO TRINIDAD GARRIDO
-- 11/2018
-- VERSION FINAL
-- NOTAS: 

-- ---------------------------------------------------------------------------------------------------------------------------------
-- CONTENIDO -----------------------------------------------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------------------------------------------------

-- ---------------------------------------------------------------------------------------------------------------------------------
-- SECCION DATOS DE LAS TABLAS DEL ESQUEMA DE ADMINISTRACION "ADM" -----------------------------------------------------------------
-- ---------------------------------------------------------------------------------------------------------------------------------

-- CATALOGO DE "ADM".Dependencias MUNICIPALES O ESTATALES 
-- CATALOGO DE "ADM".Departamentos O AREAS
-- CATALOGO DE JORNADA LABORAL
-- CATALOGO DE "ADM".Modulos DEL GEOESCRITORIO VIRTUAL
-- CATALOGO DE "ADM".Perfiles O GRUPOS DE "ADM".Usuarios
-- CATALOGO DE "ADM".Puestos
-- CATALOGO DE "ADM".Usuarios

-- TABLA RESOLUTIVA DE PERFIL CON "ADM".Modulos
-- TABLA RESOLUTIVA DE "ADM".Usuarios CON PERFIL, DEPARTAMENTO Y PUESTO


-- ---------------------------------------------------------------------------------------------------------------------------------
-- REGISTROS DEL CATALOGO DE DEPENDENCIAS MUNICIPALES O ESTATALES  -----------------------------------------------------------------
-- ---------------------------------------------------------------------------------------------------------------------------------

DELETE FROM  "ADM".RES_Perfiles_Usuarios;

DELETE FROM  "ADM".RES_Perfiles_Modulos;

DELETE FROM  "ADM".RES_Perfiles_Areas;

DELETE FROM  "ADM".Departamentos CASCADE;

DELETE FROM  "ADM".Dependencias CASCADE;

INSERT INTO  "ADM".Dependencias (Dep_Cve, Dep_Nom, Dep_Dep, Dep_Abr )
VALUES 
(nextval('"ADM".Dependencias_Dep_Cve_seq'), 'PRESIDENCIA', NULL, 'PSD'),
(nextval('"ADM".Dependencias_Dep_Cve_seq'), 'CONTRALORIA CIUDADANA', 1, 'CC'),
(nextval('"ADM".Dependencias_Dep_Cve_seq'), 'JEFATURA DE GABINETE', 1, 'JG'),
(nextval('"ADM".Dependencias_Dep_Cve_seq'), 'SINDICATURA DEL AYUNTAMIENTO', 1, 'SA'),
(nextval('"ADM".Dependencias_Dep_Cve_seq'), 'SECRETARIA DEL AYUNTAMIENTO', 1, 'SAYTO'),
(nextval('"ADM".Dependencias_Dep_Cve_seq'), 'COMISARIA GENERAL DE SEGURIDAD PUBLICA', 1, 'CGSP'),
(nextval('"ADM".Dependencias_Dep_Cve_seq'), 'TESORERIA', 1, 'T'),
(nextval('"ADM".Dependencias_Dep_Cve_seq'), 'UNIDAD DE ENLACE ADMINISTRATIVO JURIDICO PRESIDENCIA', 1, 'UEAJP'),
(nextval('"ADM".Dependencias_Dep_Cve_seq'), 'UNIDAD POLITICA', 1, 'UP'),
(nextval('"ADM".Dependencias_Dep_Cve_seq'), 'SECRETARIA PARTICULAR', 1, 'SP'),
(nextval('"ADM".Dependencias_Dep_Cve_seq'), 'COORDINACION DE ANALISIS ESTRATEGICO Y COMUNICACION', 1, 'CAEC'),
(nextval('"ADM".Dependencias_Dep_Cve_seq'), 'RELACIONES PUBLICAS PROTOCOLO Y EVENTOS', 1, 'RPPE'),
(nextval('"ADM".Dependencias_Dep_Cve_seq'), 'COORDINACION GENERAL DE CONSTRUCCION DE LA COMUNIDAD', 1, 'CGCC'),
(nextval('"ADM".Dependencias_Dep_Cve_seq'), 'COORDINACION GENERAL DE SERVICIOS MUNICIPALES', 1, 'CGSM'),
(nextval('"ADM".Dependencias_Dep_Cve_seq'), 'COORDINACION GENERAL DE ADMINISTRACION E INNOVACION GUB', 1, 'CGAIG'),
(nextval('"ADM".Dependencias_Dep_Cve_seq'), 'COORDINACION GENERAL DE DESARROLLO ECONOMICO Y COMBATE A LA', 1, 'CGDEC'),
(nextval('"ADM".Dependencias_Dep_Cve_seq'), 'COORDINACION GENERAL DE GESTION INTEGRAL DE LA CIUDAD', 1, 'CGGIC');


-- ---------------------------------------------------------------------------------------------------------------------------------
-- REGISTROS DEL CATALOG DE DEPARTAMENTOS O AREAS ----------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------------------------------------------------

INSERT INTO "ADM".Departamentos (Dpa_Cve, Dep_Cve, Dpa_Nom, Dpa_Dep, Dpa_Abr )
VALUES 
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'DIRECCION DE POLITICA FISCAL Y MEJORA HACENDARIA', NULL, 'DPFMH'),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'UNIDAD DE ENLACE ADMINISTRATIVO JURIDICO TESORERIA', 1, NULL),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'UNIDAD DE APREMIOS', 1, 'UA'),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'UNIDAD DE ATENCION A CONTRIBUYENTES', 1, 'UACONTR'),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'UNIDAD DE PROGRAMAS Y OBRA PUBLICA', 1, 'UPOP'),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'UNIDAD JURIDICA', 1, 'UJI'),

(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'DIRECCION DE PRESUPUESTO Y EGRESOS', NULL, 'DPE'),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'UNIDAD DE PAGADURIA', 7, NULL),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'UNIDAD DE PRESUPUESTO', 7, 'UP'),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'UNIDAD DE CONTROL Y SEGUIMIENTO DEL EGRESO', 7, NULL),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'UNIDAD DE EGRESOS', 7, 'UE'),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'UNIDAD DE NOMINAS', 7, NULL),

(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'DIRECCION DE CATASTRO', NULL, 'DC'),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'SECCION DE CARTOGRAFIA', 13, 'SC'),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'SECCION DE INVESTIGACION DE VALORES', 13, 'SIV'),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'SECCION DE REVISION DE AVALUOS', 13, 'SRA'),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'SECCION DE VALUACION DE CAMPO', 13, 'SVC'),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'UNIDAD DE CONTROL INTERNO CATASTRO', 13, 'UCIC'),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'UNIDAD DE TRAMITE Y REGISTRO', 13, 'UTR'),

(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'DIRECCION DE CONTABILIDAD', NULL, 'DCON'),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'UNIDAD DE ARMONIZACION CONTABLE', 20, 'UAC'),

(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'DIRECCION DE GLOSA', NULL, 'DG'),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'GLOSA DE OBRA PUBLICA Y CATASTRO', 22, 'GOPC'),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'GLOSA DEL EGRESO', 22, 'GE'),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'GLOSA DEL INGRESO', 22, 'GI'),

(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'DIRECCION DE INGRESOS', NULL, 'DI'),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'JEFATURA DE INGRESOS', 26, 'JI'),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'UNIDAD DE INGRESOS', 26, NULL),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'RECAUDADORA UNO', 26, 'R1'),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'RECAUDADORA DOS', 26, 'R2'),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'RECAUDADORA TRES', 26, 'R3'),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'RECAUDADORA CINCO', 26, 'R5'),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'RECAUDADORA SEIS', 26, 'R6'),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'RECAUDADORA OCHO', 26, 'R8'),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 7, 'UNIDAD JURIDICA INGRESOS', 26, 'UJI'),

(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 15, 'JEFATURA ADMINISTRATIVA', 33, 'JA'),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'),  5, 'JUNTA MUNICIPAL DE RECLUTAMIENTO', NULL, 'JMR'),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 13, 'MUSEO MAZ', NULL, 'MAZ'),
(nextval('"ADM".Departamentos_Dpa_Cve_seq'), 13, 'OFICINA DE APOYO OPERATIVO EDUCACION', 27, 'OAOE');


-- ---------------------------------------------------------------------------------------------------------------------------------
-- REGISTROS DEL CATALOGO DE JORNADA LABORAL ---------------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------------------------------------------------

DELETE FROM  "ADM".Jornadas;

INSERT INTO "ADM".Jornadas (Jor_Cve, Jor_Des, Jor_Dia, Jor_Hor_Ini, Jor_Hor_Fin)
VALUES 
(nextval('"ADM".Jornadas_Jor_Cve_seq'), 'SINDICAL', '{t,t,t,t,t,f,f}', '07:00:00', '15:00:00'),
(nextval('"ADM".Jornadas_Jor_Cve_seq'), 'COMPACTADA', '{t,t,t,t,t,f,f}', '08:00:00', '17:00:00'),
(nextval('"ADM".Jornadas_Jor_Cve_seq'), 'NORMAL', '{t,t,t,t,t,f,f}', '09:00:00', '18:00:00'),
(nextval('"ADM".Jornadas_Jor_Cve_seq'), 'VESPERTINA', '{t,t,t,t,t,f,f}', '14:00:00', '21:00:00'),
(nextval('"ADM".Jornadas_Jor_Cve_seq'), 'NOCTURNA', '{t,t,t,t,t,f,f}', '21:00:00', '05:00:00'),
(nextval('"ADM".Jornadas_Jor_Cve_seq'), 'MIXTA', '{t,t,t,t,t,f,f}', '17:00:00', '12:00:00'),
(nextval('"ADM".Jornadas_Jor_Cve_seq'), 'FIN DE SEMANA', '{f,f,f,f,f,t,t}', '08:00:00', '18:00:00'),
(nextval('"ADM".Jornadas_Jor_Cve_seq'), 'EXTRAORDINARIA', '{t,t,t,t,t,t,t}', '09:00:00', '22:00:00');


-- ---------------------------------------------------------------------------------------------------------------------------------
-- REGISTROS DEL CATALOGO DE MODULOS DEL GEOESCRITORIO VIRTUAL ---------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------------------------------------------------

DELETE FROM  "ADM".Modulos;

INSERT INTO "ADM".Modulos (Mod_Cve, Mod_Nom, Mod_Lik, Mod_Img, Mod_Ord, Mod_Nom_Lar, Mod_Ver, Mod_Cve_Raiz, Mod_Ext, Mod_Res )
VALUES 
(nextval('Modulos_Mod_Cve_seq'), 'ADMINISTRACION ADM', 'gev/40/adm/', 'images/iconos/gev/40/adm/.png', 1, 'ADMINISTRACION Y CONFIGURACION DE LOS USUARIOS,  GESTION DE PERFILES, PERMISOS DE INGRESO A LOS MODULOS Y OTRAS FUNCIONALIDADES DE SISTEMA.',  '1', NULL, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'USUARIOS', 'gev/40/adm/usr', 'images/iconos/gev/40/adm/usr.png', 5, 'USUARIOS',  '1', 1, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'CATALOGOS', 'gev/40/adm/cat', 'images/iconos/gev/40/adm/cat.png', 10, 'ADMINISTRACION DE CATALOGOS',  '1', 1, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'BITACORAS DE OPERACION', 'gev/40/adm/log', 'images/iconos/gev/40/adm/log.png', 15, 'CONSULTA DE BITACORAS',  '1', 1, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'BITACORAS DE RESPALDOS Y RESTAURACIONES', 'gev/40/adm/bit', 'images/iconos/gev/40/adm/bit.png', 20, 'ADMINISTRACION DE BASE DE DATOS',  '1', 1, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'RESPALDOS', 'gev/40/adm/bit/res', 'images/iconos/gev/40/adm/bit/res.png', 25, 'RESPALDOS',  '1', 20, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'RESTAURACION', 'gev/40/adm/bit/rez', 'images/iconos/gev/40/adm/bit./rez.png', 30, 'RESTAURACION',  '1', 20, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'ADMINISTRACION DE CONTENIDOS', 'gev/40/adm/con', 'images/iconos/gev/40/adm/con.png', 35, 'ADMINISTRACION DE CONTENIDOS',  '1', 1, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'ADMINISTRACION DE PARAMETROS', 'gev/40/adm/con/par', 'images/iconos/gev/40/adm/con/par.png', 40, 'MODULO PARA CONFIGURAR LOS PARAMETROS DEL SISTEMA',  '1', 35, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'FORO', 'gev/40/adm/con/for', 'images/iconos/gev/40/adm/con/for.png', 45, 'MODULO DE ADMINISTRACION DE FOROS',  '1', 35, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'ADMINISTRACION DE PREGUNTAS FRECUENTES', 'gev/40/adm/con/ask', 'images/iconos/gev/40/adm/con/ask.png', 50, 'ADMINISTRACION DE FAQ - PREGUNTAS FRECUENTES',  '1', 35, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'MANUALES', 'gev/40/adm/con/man', 'images/iconos/gev/40/adm/con/man.png', 55, 'MANUALES',  '1', 35, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'CONFIGURAR URLS', 'gev/40/adm/con/url', 'images/iconos/gev/40/adm/con/url.png', 60, 'MODULO PARA CONFIGURAR URLS',  '1', 35, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'VENTANILLA UNICA UNI', 'gev/40/uni/', 'images/iconos/gev/40/uni/.png', 65, 'VENTANILLA UNICA MUNICIPAL',  '1', NULL, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'RECEPCION DE TRAMITES Y SERVICIOS', 'gev/40/uni/rec', 'images/iconos/gev/40/uni/rec.png', 70, 'MODULO DE RECEPCION DE SOLICITUDES DE TRAMITES Y SERVICIOS',  '1', 65, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'ENTREGA DE ASUNTOS TRAMITADOS O SERVICIOS SOLICITADOS', 'gev/40/uni/ent', 'images/iconos/gev/40/uni/ent.png', 75, 'MODULO DE ENTREGA DE ASUNTOS TRAMITADOS Y SERVICIOS SOLICITADOS',  '1', 65, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'CONSULTA DE TRAMITES Y SERVICIOS VIGENTES', 'gev/40/uni/con', 'images/iconos/gev/40/uni/con.png', 80, 'MODULO DE CONSULTA DE SOLICITUDES DE TRAMITES Y SERVICIOS EN PROCESO',  '1', 65, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'INTELIGENCIA GEOGRAFICA DE NEGOCIOS SBI', 'gev/40/sbi/', 'images/iconos/gev/40/sbi/.png', 85, 'SPATIAL GEOGRAPHIC INTELLIGENCE  GEV 4.0',  '1', NULL, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'INDICADORES', 'gev/40/sbi/ind', 'images/iconos/gev/40/sbi/ind.png', 90, 'INDICADORES',  '1', 85, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'INDICADORES DE CONTROL', 'gev/40/sbi/con', 'images/iconos/gev/40/sbi/con.png', 95, 'INDICADORES DE CONTROL',  '1', 90, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'INDICADORES DE CALIDAD  EN EL SERVICIO ', 'gev/40/sbi/cal', 'images/iconos/gev/40/sbi/cal.png', 100, 'INDICADORES DE CALIDAD  EN EL SERVICIO ',  '1', 90, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'EVALUACION DE SATISFACCION', 'gev/40/sbi/eva', 'images/iconos/gev/40/sbi/eva.png', 105, 'EVALUACION DE SATISFACCION',  '1', 90, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'AUDITORIA', 'gev/40/sbi/aud', 'images/iconos/gev/40/sbi/aud.png', 110, 'AUDITORIA',  '1', 90, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'MAPAS TEMATICOS', 'gev/40/sbi/tem', 'images/iconos/gev/40/sbi/tem.png', 115, 'MAPAS TEMATICOS',  '1', 85, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'TABLERO DE CONTROL', 'gev/40/sbi/tab', 'images/iconos/gev/40/sbi/tab.png', 120, 'INTELIGENCIA ESPACIAL DE NEGOCIOS',  '1', 85, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'ADMINISTRACION DE TRAMITES Y SERVICIOS CATASTRALES KTT', 'gev/40/ftg/', 'images/iconos/gev/40/ftg/.png', 125, 'PROCESOS ADMINISTRATIVOS GEV 4.0',  '1', NULL, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'PROCESOS FRONT DESK', 'gev/40/ftg/inicio/tram_front', 'images/iconos/gev/40/ftg/inicio/tramites_front.png', 130, 'PROCESOS FRONT DESK',  '1', 125, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'PROCESOS BACK END', 'gev/40/ftg/inicio/tram_back', 'images/iconos/gev/40/ftg/inicio/tramites_back.png', 135, 'PROCESOS BACK END',  '1', 125, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'RECURSO DE REVISION', 'gev/40/ftg/inicio/tram_rev', 'images/iconos/gev/40/ftg/inicio/tramites_rev.png', 140, 'RECURSO DE REVISION',  '1', 125, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'REPORTES FTG', 'gev/40/ftg/rep', 'images/iconos/gev/40/ftg/reportes.png', 145, 'REPORTES',  '1', 125, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'CONSULTA DE ACTIVO', 'gev/40/ftg/con', 'images/iconos/gev/40/ftg/con.png', 150, 'CONSULTA DE ACTIVO',  '1', 125, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'ACTUALIZACION DE ACTIVO', 'gev/40/ftg/act', 'images/iconos/gev/40/ftg/act.png', 155, 'ACTUALIZACIÓN DE ACTIVO',  '1', 125, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'MONITOR DE PROCESOS', 'gev/40/ftg/mon', 'images/iconos/gev/40/ftg/mon.png', 160, 'MONITOR DE PROCESOS',  '1', 125, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'CONSULTA DE DOCUMENTOS', 'gev/40/ftg/doc', 'images/iconos/gev/40/ftg/doc.png', 165, 'CONSULTA DE DOCUMENTOS',  '1', 125, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'EDICION CATASTRAL GEV CATASTRO', 'gev/40/ktt/', 'images/iconos/gev/40/ktt/.png', 170, 'ADMINISTRACION CATASTRAL (KTT) GEV 4.0',  '1',  125, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'ADMINISTRACION DE INGRESOS TSR' , 'gev/40/tsr/', 'images/iconos/gev/40/tsr/.png', 175, 'TESORERIA (TSR)'                       ,  '1', NULL, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'INGRESOS', 'gev/40/tsr/ing', 'images/iconos/gev/40/tsr/ing.png', 180, 'INGRESOS',  '1', 170, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'CONFIGURACION ANUAL DEL EJERCICIO', 'gev/40/ktt/', 'images/iconos/gev/40/ktt/.png', 185, 'ADMINISTRACION CATASTRAL (KTT) GEV 4.0',  '1', 170, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'REPORTES TSR', 'gev/40/tsr/egr', 'images/iconos/gev/40/tsr/egr.png', 185, 'REPORTES',  '1', 170, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'INFRAESTRUCTURA DE DATOS ESPACIALES IDE', 'gev/40/ide/', 'images/iconos/gev/40/ide/.png', 190, 'INFRAESTRUCTURA DE DATOS ESPACIALES (IDE)  GEV 4.0',  '1', NULL, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'GEOPORTAL DE REFERENCIA', 'gev/40/ide/ref', 'images/iconos/gev/40/ide/ref.png', 195, 'GEOPORTAL DE REFERENCIA',  '1', 190, 'f', 0),
(nextval('Modulos_Mod_Cve_seq'), 'GEOPORTAL SUSTANTIVO', 'gev/40/ide/sus', 'images/iconos/gev/40/ide/sus.png', 200, 'GEOPORTAL SUSTANTIVO',  '1', 190, 'f', 1);


-- ---------------------------------------------------------------------------------------------------------------------------------
-- REGISTROS DEL  CATALOGO DE PERFILES O GRUPOS DE USUARIOS ------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------------------------------------------------

DELETE FROM  "ADM".Perfiles;

INSERT INTO "ADM".Perfiles (Per_Cve, Per_Nom, Per_Des, Per_Res, Per_Com )
VALUES 
(nextval('"ADM".Perfiles_Per_Cve_seq'), 'SUPERUSUARIO', 'SUPERUSUARIO DEL GEV 4.0', 0,  'SUPERUSR'),
(nextval('"ADM".Perfiles_Per_Cve_seq'), 'ADMINISTRADOR DEL SISTEMA EN DESARROLLO', 'ADMINISTRADOR DEL SISTEMA', 1,  'ADM_AMB_DEV'),
(nextval('"ADM".Perfiles_Per_Cve_seq'), 'ADMINISTRADOR DE CAMPO', 'ADMINISTRADOR DE CAMPO', 1,  'ADM_TRA_CAM'),
(nextval('"ADM".Perfiles_Per_Cve_seq'), 'ADMINISTRADOR DE TRATAMIENTO DEL DATO', 'ADMINISTRADOR DE TRATAMIENTO DEL DATO', 1,  'ADM_TRT_MIG_DAT'),
(nextval('"ADM".Perfiles_Per_Cve_seq'), 'ADMINISTRADOR ADM', 'ADMINISTRACION ADMINISTRACION', 2,  'ADM'),
(nextval('"ADM".Perfiles_Per_Cve_seq'), 'ADMINISTRADOR SBI', 'ADMINISTRACION INTELIGENCIA ESPACIAL DE NEGOCIOS', 2,  'SBI'),
(nextval('"ADM".Perfiles_Per_Cve_seq'), 'ADMINISTRADOR FTG', 'ADMINISTRACION FLUJO DE TRABAJO GEOGRAFICO', 2,  'FTG'),
(nextval('"ADM".Perfiles_Per_Cve_seq'), 'ADMINISTRADOR TSR', 'ADMINISTRACION TESORERIA', 2,  'TSR'),
(nextval('"ADM".Perfiles_Per_Cve_seq'), 'ADMINISTRADOR KTT', 'ADMINISTRACION CATASTRAL', 2,  'KTT'),
(nextval('"ADM".Perfiles_Per_Cve_seq'), 'ADMINISTRADOR IDE', 'ADMINISTRACION INFRAESTRUCTURA DE DESARROLLO ESPACIAL', 2,  'IDE'),
(nextval('"ADM".Perfiles_Per_Cve_seq'), 'ADMINISTRADOR UNI', 'ADMINISTRACION VENTANILLA UNICA', 2,  'UNI'),
(nextval('"ADM".Perfiles_Per_Cve_seq'), 'EJECUTIVO UNI', 'EJECUTIVO VENTANILLA UNICA', 3,  'EJE_UNI'),
(nextval('"ADM".Perfiles_Per_Cve_seq'), 'EJECUTIVO SBI', 'EJECUTIVO  INTELIGENCIA ESPACIAL DE NEGOCIOS', 3,  'EJE_SBI'),
(nextval('"ADM".Perfiles_Per_Cve_seq'), 'EJECUTIVO FTG', 'EJECUTIVO FLUJO DE TRABAJO GEOGRAFICO', 3,  'EJE_FTG'),
(nextval('"ADM".Perfiles_Per_Cve_seq'), 'EJECUTIVO TSR', 'EJECUTIVO TESORERIA', 3,  'EJE_TSR'),
(nextval('"ADM".Perfiles_Per_Cve_seq'), 'EJECUTIVO KTT', 'EJECUTIVO CATASTRAL', 3,  'EJE_KTT'),
(nextval('"ADM".Perfiles_Per_Cve_seq'), 'SUPERVISION UNI', 'SUPERVISION VENTANILLA UNICA', 4,  'SUP_FTG'),
(nextval('"ADM".Perfiles_Per_Cve_seq'), 'SUPERVISION FTG', 'SUPERVISION FLUJO DE TRABAJO GEOGRAFICO', 4,  'SUP_FTG'),
(nextval('"ADM".Perfiles_Per_Cve_seq'), 'SUPERVISION TSR', 'SUPERVISION TESORERIA', 4,  'SUP_TSR'),
(nextval('"ADM".Perfiles_Per_Cve_seq'), 'SUPERVISION KTT', 'SUPERVISION CATASTRAL', 4,  'SUP_KTT'),
(nextval('"ADM".Perfiles_Per_Cve_seq'), 'OPERADOR PROCESAL UNI', 'OPERADOR PROCESAL VENTANILLA UNICA', 5,  'OPD_ FTG'),
(nextval('"ADM".Perfiles_Per_Cve_seq'), 'OPERADOR PROCESAL FTG', 'OPERADOR PROCESAL FLUJO DE TRABAJO GEOGRAFICO', 5,  'OPD_ FTG'),
(nextval('"ADM".Perfiles_Per_Cve_seq'), 'OPERADOR INGRESOS TSR', 'OPERADOR INGRESOS  TESORERIA', 5,  'OPD_ TSR'),
(nextval('"ADM".Perfiles_Per_Cve_seq'), 'OPERADOR CARTOGRAFICO KTT', 'OPERADOR CARTOGRAFICO  CATASTRAL', 5,  'OPD_ KTT'),
(nextval('"ADM".Perfiles_Per_Cve_seq'), 'OPERADOR IDE', 'OPERADOR INFRAESTRUCTURA DE DESARROLLO ESPACIAL', 5,  'OPD_ IDE');


-- ---------------------------------------------------------------------------------------------------------------------------------
-- REGISTROS DEL CATALOGO DE PUESTOS -----------------------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------------------------------------------------

DELETE FROM  "ADM".Puestos;

INSERT INTO "ADM".Puestos (Pue_Cve, Pue_Des, Pue_Prior )
VALUES 
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'TRASLADO DE DOMINIO REVISION ADMINISTRATIVA', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'TRASLADO DE DOMINIO OPERACION', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'TRASLADO DE DOMINIO DICTAMEN', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'TRASLADO DE DOMINIO', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'TRANSMISION PATRIMONIAL REVISOR TECNICO ', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'TRANSMISION PATRIMONIAL REVISOR ADMINISTRATIVO', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'TRANSMISION PATRIMONIAL RECEPCIONISTA ', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'TRANSMISION PATRIMONIAL AUXILIAR DE  ESCANEO ', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'TESORERO', 0),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'SUPERVISOR DE COBRO DE IMPUESTO PREDIAL', 2),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'SUPERVISOR DE CATASTRO', 2),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'SUPERVISOR DE CAJAS', 2),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'SUPERVISOR DE ADMINISTRACION', 2),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'REVISOR TECNICO', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'REVISOR DE GLOSA', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'REVISOR ADMINISTRATIVO CONSTANCIAS', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'REVISOR ADMINISTRATIVO', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'REPORTES', 2),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'RECEPCION Y ENTREGA RECEPCIONISTA ', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'RECEPCION Y ENTREGA AUXILIAR DE ESCANEO ', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'PROBADOR UNI', 1),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'PROBADOR TSR', 1),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'PROBADOR KTT', 1),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'PROBADOR FTG', 1),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'PRESIDENTE MUNICIPAL', 0),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'OPERADOR DE  IDE', 1),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'OFICIALIA DE PARTES RECEPCIONISTA ', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'NOTARIO CAPTURISTA DE ', 4),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'NOTARIO', 4),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'MULTITRAMITE TRANSMISION PATRIMONIAL', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'MULTITRAMITE REVISOR TECNICO ', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'MULTITRAMITE REVISOR ADMINISTRATIVO ', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'MULTITRAMITE RECEPCIONISTA', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'MULTITRAMITE AUXILIAR DE ESCANEO ', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'INVESTIGACION DE VALOR', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'GABINETE JURIDICO CON ABSTENCION', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'GABINETE JURIDICO', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'GABINETE JEFE JURIDICO', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'GABINETE HISTORIAL', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'GABINETE CON ACTO DE AUTORIDAD', 2),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'EMISION DE CONSTANCIAS', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'EJECUTIVO UNI', 1),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'EJECUTIVO TSR FISCAL', 1),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'EJECUTIVO SBI', 1),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'EJECUTIVO KTT', 1),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'EJECUTIVO FTG', 1),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'DIRECTOR DE CATASTRO', 1),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'DESARROLLADOR PROCESAL UNI', 1),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'DESARROLLADOR PROCESAL FTG', 1),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'DESARROLLADOR INGRESOS TSR', 1),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'DESARROLLADOR IDE', 1),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'DESARROLLADOR CARTOGRAFICO KTT', 1),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'COORDINADOR', 1),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'CONTROL INTERNO', 2),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'CONTROL DE FOLIOS', 2),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'CATASTRO OPERADOR DE TRAMITES', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'CATASTRO OPERADOR DE EDICION CARTOGRAFICA LIMITADO', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'CATASTRO OPERADOR DE EDICION CARTOGRAFICA', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'CATASTRO OPERADOR DE CONSULTA', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'CATASTRO INTEGRADOR CARTOGRAFICO', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'CATASTRO ACTUALIZACION CARTOGRAFICA', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'CAMPO INVESTIGADOR', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'CAMPO BRIGADA TOPOGRAFICA', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'CAMPO AUTORIZACION', 2),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'CAMPO', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'CALIFICADOR', 2),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'CAJERO', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'AVALUO VALUADOR REVISOR', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'AVALUO VALUADOR AUTORIZADO', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'AVALUO VALUADOR', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'AVALUO REVISOR TECNICO  ACTO DE AUTORIDAD', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'AVALUO REVISOR TECNICO ', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'AVALUO REVISOR ADMINISTRATIVO ', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'AVALUO EXTERNO REVISOR TECNICO ', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'AVALUO EXTERNO REVISOR ADMINISTRATIVO ', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'AVALUO EXPRESS', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'AVALUO AUXILIAR DE  ESCANEO ', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'AUTORIZACION DIRECCION', 1),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'ATENCION CONTRIBUYENTE', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'ASISTENTE DE LA DIRECCION', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'AREA FISCAL', 3),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'ADMINISTRADOR UNI', 1),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'ADMINISTRADOR TSR PREDIAL', 1),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'ADMINISTRADOR TSR', 1),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'ADMINISTRADOR SBI', 1),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'ADMINISTRADOR KTT', 1),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'ADMINISTRADOR IDE', 1),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'ADMINISTRADOR FTG', 1),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'ADMINISTRADOR DEL SISTEMA TI', 1),
(nextval('"ADM".Puestos_Pue_Cve_seq'), 'ADMINISTRADOR ADM', 1);


-- ---------------------------------------------------------------------------------------------------------------------------------
-- REGISTROS DEL CATALOGO DE USUARIOS  ---------------------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------------------------------------------------

DELETE FROM  "ADM".Usuarios;

INSERT INTO  "ADM".Usuarios (Usu_Id, Usu_Usr, Usu_Pas,  Edo_Cve, Reg_Cat_Cve, Mun_Cve, Loc_Cve, Usu_Tpo_Usr, Usu_Pat, Usu_Mat, Usu_Nom, Usu_Aut_Quita, Usu_Tel, Usu_Ext, Usu_Mac, Usu_Email, Usu_Smtp_host, Usu_Smtp_Pto, Usu_Ubi, Usu_Obs, Usu_Adm, Usu_Fot, Usu_Arc, Usu_Xet)
VALUES
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'SUPERUSUARIO', 'aLos3', 14, 12, 120, 1, 't', 'SUPER', 'USUARIO', 'ADMIN', 'f', '(55)-30-13-22-86', '2351','00:1e:c2:9e:28:6b', 'geoware@geoware.com.mx', 'smtp.gmail.com', 587, NULL, NULL, 't', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'ADM_FTG_001', 'Yb]uacOQ=DK[o|lF', 14, 12, 120, 1, 't', 'REYES', 'REYES', 'RUBEN ', 'f', '(55)-30-13-22-86', '2352', '00:1e:c2:9e:28:6b', 'geoware@geoware.com.mx', 'smtp.gmail.com', 587, NULL, NULL, 't', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'ADM_SBI_001', 'hcODKmic', 14, 12, 120, 1, 't', 'ELIZALDE', 'ELIZALDE', 'REBECA', 'f', '(55)-30-13-22-86', '2353',  '00:1e:c2:9e:28:6b', 'geoware@geoware.com.mx', 'smtp.gmail.com', 587, NULL, NULL, 't', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'ADM_ADM_001', 'Gc-~|V2q147RlyqL', 14, 12, 120, 1, 't', 'G', 'DELSIS', 'A', 'f', '(55)-30-13-22-86', '2354',  '00:1e:c2:9e:28:6b', 'csanchez@geoware.com.mx', 'smtp.gmail.com', 587, NULL, NULL, 't', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'ADM_AMB_DEV_001', 'FI"FIi6uP-^7YrFm68Pct', 14, 12, 120, 1, 't', 'TRINIDAD', 'GARRIDO', 'FRANCISCO', 'f', '(55)-30-13-22-86', '2355', '00:1e:c2:9e:28:6b', 'fgarrido@geoware.com.mx', 'smtp.gmail.com', 587, NULL, NULL, 't', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'ADM_CveE_001', 'lBN]dSMvwgP%mpbA2^c}', 14, 12, 120, 1, 't', 'RUIZ', 'CORTES', 'DIEGO', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'jcanizares@geoware.com.mx', 'smtp.gmail.com', 587, NULL, NULL, 't', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'ADM_TRA_CAM_001', 'hfru{;u-9]74PNtM6Z@j', 14, 12, 120, 1, 't', 'DEL', 'GEV', 'CATASTRO', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'catastro_17@geoware.com.mx', 'smtp.gmail.com', 587, NULL, NULL, 't', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'ADM_TRT_MIG_DAT_001', '|6evNhhHs3P1', 14, 12, 120, 1, 't', 'SANCHEZ', 'CRUZ', 'CARLOS', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'csanchez@geoware.com.mx', 'smtp.gmail.com', 587, NULL, NULL, 't', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'ADM_TSR_002', 'vWBLh6asMq2%GZ}Tol', 14, 12, 120, 1, 't', 'DEL', 'GEV', 'ADMINCIP', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'admincip_17@geoware.com.mx', 'smtp.gmail.com', 587, NULL, NULL, 't', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'ADM_TSR-001', 'xrSn-j*XR}|1AHlqM6', 14, 12, 120, 1, 't', 'DEL', 'GEV', 'ADMINTS', 'f','(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'admints@geoware.com.mx', 'smtp.gmail.com', 587, NULL, NULL, 't', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'EJE_FTG_001', 'sJjvQImOuBLAYfXIF', 14, 12, 120, 1, 't', 'ESPINOZA', 'TORRES', 'OMAR', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'oespinoza@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'EJE_FTG_002', 'J6wmfRG775b0j6w9Z', 14, 12, 120, 1, 't', 'FIGUEROA', 'DELGADO', 'ANA BEATRIZ', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'figueroa@zapopan.gob.mx', 'smtp.gmail.com', 587, 'mazateopan', '50', 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'EJE_KTT_001', '0dAqq52jj1Fs0qqqK', 14, 12, 120, 1, 't', 'FLORES', 'GASPAR', 'DANIEL', 'f','(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'dflores@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'EJE_KTT_002', 'I175WDOryt5Kyl2t1', 14, 12, 120, 1, 't', 'FLORES', 'MORALES', 'JUAN ANTONIO', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'jflores@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'EJE_KTT_17', 'PmcvV6aVesltH2cIl', 14, 12, 120, 1, 't', 'DEL', 'GEV', 'OPERCONSULTA', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'operconsulta_17@geoware.com.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'EJE_SBI_001', 'NGRMERCNoNcDvQyZh', 14, 12, 120, 1, 't', 'ESCOBEDO', 'CAMARILLO', 'SANDRA', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'sescobedo@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'EJE_SBI_002', 'vWBLh6asMq2%GZ}Tol', 14, 12, 120, 1, 't', 'ESPARZA', 'GONZALEZ', 'GABRIELA', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'gabriela@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'EJE_TSR_001', 'pwJUBiJ0Wc', 14, 12, 120, 1, 't', 'FLORES', 'FLORES', 'RICARDO', 't', '(55)-30-13-22-86', NULL, '00:1e:c2:9e:28:6b', 'rflores@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'EJE_TSR_002', 'BIdkBbWjpT', 14, 12, 120, 1, 't', 'FLORES', 'GAMEZ', 'DAVID', 't', '(33)-38-22-38-99', NULL, '00:1e:c2:9e:28:6b', 'david@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_FTG_001', 'FqGY9BAwAT', 14, 12, 120, 1, 't', 'ACOSTA', 'SANTIAGO', 'ANA LUISA', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'aacosta@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_FTG_002', 'td1GrjTjRD', 14, 12, 120, 1, 't', 'AGUILAR', 'GARCIA', 'MARCELA', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'correo@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_FTG_003', 'wGXFDHDHlN', 14, 12, 120, 1, 't', 'ALVAREZ', 'GONZALEZ', 'ERNESTO', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'ealvarez@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_FTG_004', 'sLYJRKNYse', 14, 12, 120, 1, 't', 'ALVAREZ', 'PEREZ', 'BERTHA', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'bertha@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_FTG_005', 'UvSTMPgtH7', 14, 12, 120, 1, 't', 'ANGEL', 'NUÑEZ', 'MARIBEL', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'mangel@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_FTG_EXT_001', '2f9g8Y41nU', 14, 12, 120, 1, 'f', 'MAYORAL', 'URIBE', 'ANA LAURA', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'anamayoral@mayoral-abogados.com','smtp.gmail.com', 587, 'GUADALAJARA ', '48', 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_FTG_EXT_002', 'uubgOe0BiK', 14, 12, 120, 1, 'f', 'BEAZ', 'PEREZ', 'SERGIO MANUEL ', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'notario112beas@hotmail.com', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_CveE_001', 'ndnJtSjW:bE0', 14, 12, 120, 1, 't', 'CARRILLO', 'POBLANO', 'CARLOS', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'ccarrillo@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_CveE_002', 'm]QHCe[:y@X1', 14, 12, 120, 1, 't', 'CASTAÑEDA', 'N', 'GEORGINA', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'acazares@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_CveE_003', 'ta^U+[a{7vqv', 14, 12, 120, 1, 't', 'CASTAÑEDA', 'VILLASEÑOR', 'ALMA GEORGINA', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'alma@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_CveE_004', '[rK7qj*66Rtj', 14, 12, 120, 1, 't', 'CASTILLO', 'SANCHEZ', 'ALMA ROSA', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'acastillo@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_CveE_005', 'atsAppcome72', 14, 12, 120, 1, 't', 'CASTILLO', 'SANCHEZ', 'AIDA', 'f', '(33)-38-22-38-99', '4444', '00:1e:c2:9e:28:6b', 'aida@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_ IDE_006', 'rorenBahQ5Ur', 14, 12, 120, 1, 't', 'CASTILLO', 'SANTANA', 'RICARDO', 'f', '(33)-38-22-38-99', NULL,'00:1e:c2:9e:28:6b', 'ricardo@zapopan.gob.mx','smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_CveE_007', '=-Colombia.MH', 14, 12, 120, 1, 't', 'CASTILLON', 'CANO', 'RAMIRO ALEJANDRO', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'ramiro@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_CveE_008', 'vWBLh6asMq2%GZ}Tol', 14, 12, 120, 1, 't', 'CAZARES', 'ALVARADO', 'ADRIANA', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'acazares@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_CveE_009', 'yNEjRhIR', 14, 12, 120, 1, 't', 'CERVANTES', 'ARIZMENDI', 'GILBERTO', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'gilberto@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_CveE_010', 'orldofWarosU', 14, 12, 120, 1, 't', 'CERVANTES', 'PIZANO', 'RAFAEL', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'rafael@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_KTT', 'aSpotify-LCq', 14, 12, 120, 1, 't', 'DEL', 'GEV', 'TOPOGRAFIA', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'topografia_17@geoware.com.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_KTT_001', 'QuestXI''eYZ1', 14, 12, 120, 1, 't', 'DEL', 'GEV', 'OPERCARTOGRAFICA', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'opercartografica_17@geoware.com.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_KTT_001', 'T~=d-98%rQb{', 14, 12, 120, 1, 't', 'BEAS', 'CASARRUBIAS', 'SERGIO ', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'sergio@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_ KTT_002', 'Iu3B3l]C{9iD', 14, 12, 120, 1, 't', 'BENITES', 'PLASENCIA', 'MARIA ESMERALDA ', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'ebenitez@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_KTT_003', '7Gn0@z~QmJDX', 14, 12, 120, 1, 't', 'BOBADILLA', 'REYES', 'CRISTINA', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'bobadilla@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_KTT_004', 'b;7d\2M+SH|f', 14, 12, 120, 1, 't', 'BOLAÑOS', 'OLVERA', 'MARIA ISABEL', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'bolanos@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_KTT_005', '0R0-XtvOByl+', 14, 12, 120, 1, 't', 'CAMPOS', 'AGUILERA', 'CLIO', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'campos@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_KTT_17', 'porFortniQ17', 14, 12, 120, 1, 't', 'DEL', 'GEV', 'CATASTROUNO', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'catastrouno_17@geoware.com.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_KTT_VNT_001', 'ELUPConoFDGk', 14, 12, 120, 1, 't', 'DEL', 'GEV', 'VENTANILLA', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'ventanilla_17@geoware.com.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_TSR_001', 'AIRy6JvEu0', 14, 12, 120, 1, 't', 'ARCE', 'ULLOA', 'HECTOR', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'adriana@zapopan.gob.mx', 'smtp.gmail.com', 587, 'GUADALAJARA', '54', 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_TSR_002', 'TtKS4kWcLY', 14, 12, 120, 1, 't', 'ARELLANO', 'MACIAS', 'SANDRA', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'sarellano@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_TSR_003', 'a1YXwe6aZT', 14, 12, 120, 1, 't', 'ARRELLANO', 'FELIX', 'ALMA LETICIA', 'f','(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'alma@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_TSR_004', 'WHphN9yswaPrl9Sfd', 14, 12, 120, 1, 't', 'BARRAGAN', 'LIMON', 'CARLOS ARTURO', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'cbarragan@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_TSR_005', 'YWQCW2U8XTPT2EVPr', 14, 12, 120, 1, 't', 'BARRERA ', 'BECERRA ', 'ROCIO LIVIER ', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'rocio@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_ TSR_17', 'wERQ0iE69YWQgZkNo', 14, 12, 120, 1, 't', 'DEL', 'GEV', 'OPERTRAMITES', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'opertramites_17@geoware.com.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_TSR_MULTI_001', '0OYrrjaL05JEViMgV', 14, 12, 120, 1, 't', 'GEORGINA', 'CASTAÑEDA', 'ALMA', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'alma_multi@hotmail.com', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'OPD_TSR_MULTI_002', 'Yq4gG8EYYhLZJkT8o', 14, 12, 120, 1, 't', 'MACIEL', 'MACIEL', 'SUSANA', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'smaciel@hotmail.com', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'SUP_FTG_001', 'SpcXQlYLmg1pjgdR6f', 14, 12, 120, 1, 't', 'CHAVEZ ', 'CORTES ', 'RENE JAIRZHINNO', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'rene@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'SUP_FTG_002', 'BrAJDZkOxPMntox14g', 14, 12, 120, 1, 't', 'CORONA', 'ARIAS', 'ELVIA JUDITH', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'elvia@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'SUP_FTG_003', 'mdMwGyAvteuy8rDGEl', 14, 12, 120, 1, 't', 'CRUZ', 'MORELOS', 'JOSE DE JESUS', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'jose@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'SUP_KTT_001', ';mMwN[8v4qw5lO;~Wc', 14, 12, 120, 1, 't', 'DOMINGUEZ', 'RIVERO', 'MANUEL ', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'manuel@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'SUP_KTT_002', 'I9VKy:|g8D"Q|l^GB-', 14, 12, 120, 1, 't', 'ENCISO', 'MAGALLON', 'JOSE MIGUEL', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'jenciso@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'SUP_KTT_003', 'uxBv3C6%PNlme\@uD8', 14, 12, 120, 1, 't', 'EQUIHUA', 'GONZALEZ', 'GUADALUPE', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'guadalupe@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'SUP_TSR_001', 'yTe;}X^rcx5E}4', 14, 12, 120, 1, 't', 'CUELLAR', 'CERVANTES', 'ROCIO', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'rocio@zapopan.gob.mx', 'smtp.gmail.com', 587, 'CONSULTA', NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'SUP_TSR_002', 'WW6Z0M|SD;E;yB', 14, 12, 120, 1, 't', 'DE LA CRUZ', 'HERNANDEZ', 'PAUL', 'f','(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'paul@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL),
(nextval('"ADM".Usuarios_Usu_Id_seq'), 'SUP_TSR_003', 'nh-QRNY*+dE;', 14, 12, 120, 1, 't', 'DE LA GARZA', 'RUIZ', 'MA GUADALUPE MARISOL', 'f', '(55)-30-13-22-86', NULL,  '00:1e:c2:9e:28:6b', 'mgarza@zapopan.gob.mx', 'smtp.gmail.com', 587, NULL, NULL, 'f', NULL, NULL, NULL);


-- ---------------------------------------------------------------------------------------------------------------------------------
-- REGISTROS DE  RES_PERFILES_MODULOS ----------------------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------------------------------------------------

INSERT INTO "ADM".RES_Perfiles_Modulos(Per_Mod_Con, Per_Cve, Mod_Cve, Per_Mod_Est ) 
VALUES

(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 1, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 2, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 3, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 4, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 5, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 6, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 7, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 8, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 9, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 10, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 11, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 12, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 13, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 14, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 15, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 16, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 17, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 18, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 19, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 20, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 21, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 22, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 23, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 24, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 25, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 26, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 27, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 28, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 29, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 30, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 31, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 32, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 33, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 34, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 35, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 36, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 37, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 38, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 39, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 40, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 41, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 1, 42, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 2, 15, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 2, 16, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 2, 17, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 2, 18, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 2, 19, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 2, 20, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 2, 21, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 2, 22, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 2, 23, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 2, 24, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 2, 25, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 2, 26, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 2, 27, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 2, 28, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 2, 29, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 2, 30, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 2, 31, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 2, 32, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 2, 33, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 2, 34, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 2, 35, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 2, 36, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 2, 37, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 2, 38, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 2, 39, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 2, 40, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 2, 41, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 2, 42, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 3, 15, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 3, 16, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 3, 17, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 3, 26, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 3, 27, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 3, 28, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 3, 29, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 3, 30, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 3, 31, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 3, 32, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 3, 33, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 3, 34, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 3, 35, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 3, 36, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 3, 37, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 3, 38, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 3, 39, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 3, 40, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 3, 41, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 3, 42, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 4, 26, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 4, 27, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 4, 28, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 4, 29, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 4, 30, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 4, 31, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 4, 32, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 4, 33, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 4, 34, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 4, 35, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 4, 36, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 4, 37, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 4, 38, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 4, 39, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 4, 40, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 4, 41, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 4, 42, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 5, 1, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 5, 2, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 5, 3, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 5, 4, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 5, 5, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 5, 6, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 5, 7, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 5, 8, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 5, 9, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 5, 10, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 5, 11, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 5, 12, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 5, 13, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 5, 14, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 6, 18, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 6, 19, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 6, 20, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 6, 21, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 6, 22, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 6, 23, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 6, 24, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 6, 25, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 7, 26, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 7, 27, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 7, 28, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 7, 29, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 7, 30, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 7, 31, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 7, 32, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 7, 33, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 7, 34, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 7, 35, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 8, 36, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 8, 37, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 8, 38, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 8, 39, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 9, 35, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 10, 18, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 10, 19, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 10, 20, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 10, 21, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 10, 22, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 10, 23, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 10, 24, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 10, 25, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 11, 14, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 11, 15, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 11, 16, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 11, 17, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 12, 14, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 12, 15, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 12, 16, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 12, 17, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 13, 18, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 13, 19, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 13, 20, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 13, 21, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 13, 22, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 13, 23, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 13, 24, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 13, 25, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 14, 26, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 14, 27, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 14, 28, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 14, 29, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 14, 30, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 14, 31, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 14, 32, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 14, 33, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 14, 34, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 14, 35, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 15, 36, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 15, 37, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 15, 38, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 15, 39, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 16, 35, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 17, 14, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 17, 15, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 17, 16, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 17, 17, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 18, 26, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 18, 27, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 18, 28, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 18, 29, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 18, 30, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 18, 31, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 18, 32, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 18, 33, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 18, 34, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 19, 36, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 19, 37, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 19, 38, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 19, 39, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 20, 35, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 21, 14, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 21, 15, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 21, 16, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 21, 17, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 22, 26, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 22, 27, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 22, 28, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 22, 29, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 22, 30, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 22, 31, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 22, 32, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 22, 33, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 22, 34, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 23, 36, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 23, 37, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 23, 38, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 23, 39, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 24, 35, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 25, 40, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 25, 41, 't'),
(nextval('"ADM".RES_Perfiles_Modulos_per_mod_con_seq'), 25, 42, 't');


-- ---------------------------------------------------------------------------------------------------------------------------------
-- REGISTROS DE  RES_PERFILES_USUARIOS ---------------------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------------------------------------------------

DELETE FROM "ADM".RES_Perfiles_Usuarios;

INSERT INTO "ADM".RES_Perfiles_Usuarios (Per_Usr_Con, Per_Cve, Dpa_Cve, Pue_Cve, Jor_Cve, Usu_Id, Per_Usr_Fec_Ini_Pos, Per_Usr_Fec_Fin_Pos, Per_Usr_Est_Act )
VALUES 
(nextval('"ADM".RES_Perfiles_Usuarios_per_usr_con_seq'),  1, 13, 80, 8,  1, '2018-01-01 00:00:00', NULL, 't'),

(nextval('"ADM".RES_Perfiles_Usuarios_per_usr_con_seq'),  5, 13, 78, 8,  2, '2018-01-01 00:00:00', NULL, 't'),
(nextval('"ADM".RES_Perfiles_Usuarios_per_usr_con_seq'),  5, 13, 78, 8,  3, '2018-01-01 00:00:00', NULL, 't'),
(nextval('"ADM".RES_Perfiles_Usuarios_per_usr_con_seq'),  5, 13, 78, 8,  4, '2018-01-01 00:00:00', NULL, 't'),
(nextval('"ADM".RES_Perfiles_Usuarios_per_usr_con_seq'),  5, 13, 78, 8,  5, '2018-01-01 00:00:00', NULL, 't'),
(nextval('"ADM".RES_Perfiles_Usuarios_per_usr_con_seq'),  5, 13, 78, 8,  6, '2018-01-01 00:00:00', NULL, 't'),
(nextval('"ADM".RES_Perfiles_Usuarios_per_usr_con_seq'),  5, 13, 78, 8,  7, '2018-01-01 00:00:00', NULL, 't'),
(nextval('"ADM".RES_Perfiles_Usuarios_per_usr_con_seq'),  5, 13, 78, 8,  8, '2018-01-01 00:00:00', NULL, 't'),
(nextval('"ADM".RES_Perfiles_Usuarios_per_usr_con_seq'),  5, 13, 78, 8,  9, '2018-01-01 00:00:00', NULL, 't'),
(nextval('"ADM".RES_Perfiles_Usuarios_per_usr_con_seq'),  5, 13, 78, 8, 10, '2018-01-01 00:00:00', NULL, 't'),
(nextval('"ADM".RES_Perfiles_Usuarios_per_usr_con_seq'),  6, 13, 75, 8, 15, '2018-01-01 00:00:00', NULL, 't'),
(nextval('"ADM".RES_Perfiles_Usuarios_per_usr_con_seq'),  7, 13, 76, 8, 25, '2018-01-01 00:00:00', NULL, 't'),
(nextval('"ADM".RES_Perfiles_Usuarios_per_usr_con_seq'),  8, 13, 78, 8, 51, '2018-01-01 00:00:00', NULL, 't'),
(nextval('"ADM".RES_Perfiles_Usuarios_per_usr_con_seq'),  9, 13, 74, 8, 37, '2018-01-01 00:00:00', NULL, 't'),
(nextval('"ADM".RES_Perfiles_Usuarios_per_usr_con_seq'),  9, 13, 74, 8, 38, '2018-01-01 00:00:00', NULL, 't'),
(nextval('"ADM".RES_Perfiles_Usuarios_per_usr_con_seq'),  9, 13, 74, 8, 44, '2018-01-01 00:00:00', NULL, 't'),
(nextval('"ADM".RES_Perfiles_Usuarios_per_usr_con_seq'),  9, 13, 74, 8, 45, '2018-01-01 00:00:00', NULL, 't'),
(nextval('"ADM".RES_Perfiles_Usuarios_per_usr_con_seq'), 10, 13, 79, 8, 35, '2018-01-01 00:00:00', NULL, 't');


-- ----------------------------
-- Records of res_perfiles_areas
-- ----------------------------

INSERT INTO "ADM".RES_Perfiles_Areas 
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 1, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 2, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 3, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 4, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 5, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 6, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 7, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 8, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 9, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 10, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 11, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 12, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 13, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 14, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 15, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 16, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 17, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 18, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 19, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 20, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 21, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 22, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 23, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 24, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 25, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 26, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 27, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 28, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 29, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 30, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 31, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 32, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 33, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 34, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 35, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 36, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 37, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 38, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 1, 39, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 1, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 2, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 3, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 4, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 5, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 6, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 7, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 8, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 9, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 10, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 11, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 12, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 13, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 14, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 15, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 16, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 17, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 18, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 19, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 20, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 21, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 22, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 23, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 24, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 25, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 26, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 27, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 28, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 29, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 30, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 31, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 32, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 33, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 34, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 35, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 36, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 37, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 38, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 2, 39, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 3, 13, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 3, 14, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 3, 15, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 3, 16, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 3, 17, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 3, 18, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 3, 19, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 4, 13, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 4, 14, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 4, 15, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 4, 16, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 4, 17, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 4, 18, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 4, 19, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 1, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 2, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 3, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 4, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 5, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 6, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 7, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 8, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 9, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 10, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 11, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 12, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 20, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 21, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 22, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 23, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 24, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 25, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 26, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 27, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 28, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 29, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 30, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 31, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 32, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 33, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 34, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 35, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 36, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 37, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 38, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 5, 39, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 6, 13, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 6, 14, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 6, 15, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 6, 16, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 6, 17, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 6, 18, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 6, 19, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 6, 26, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 6, 27, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 6, 28, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 6, 29, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 6, 30, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 6, 31, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 6, 32, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 6, 33, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 6, 34, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 7, 13, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 7, 14, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 7, 15, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 7, 16, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 7, 17, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 7, 18, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 7, 19, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 8, 1, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 8, 2, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 8, 3, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 8, 4, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 8, 5, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 8, 6, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 8, 7, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 8, 8, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 8, 9, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 8, 10, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 8, 11, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 8, 12, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 8, 20, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 8, 21, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 8, 22, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 8, 23, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 8, 24, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 8, 25, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 8, 26, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 8, 27, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 8, 28, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 8, 29, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 8, 30, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 8, 31, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 8, 32, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 8, 33, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 8, 34, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 8, 35, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 9, 13, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 9, 14, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 9, 15, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 9, 16, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 9, 17, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 9, 18, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 9, 19, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 10, 13, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 10, 14, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 11, 4, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 11, 19, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 12, 4, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 12, 19, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 13, 1, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 13, 13, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 13, 20, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 13, 26, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 14, 13, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 14, 14, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 14, 15, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 14, 16, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 14, 17, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 14, 18, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 14, 19, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 15, 1, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 15, 2, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 15, 3, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 15, 4, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 15, 5, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 15, 6, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 15, 7, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 15, 8, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 15, 9, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 15, 10, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 15, 11, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 15, 12, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 15, 20, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 15, 21, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 15, 22, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 15, 23, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 15, 24, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 15, 25, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 15, 26, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 15, 27, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 15, 28, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 15, 29, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 15, 30, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 15, 31, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 15, 32, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 15, 33, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 15, 34, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 15, 35, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 15, 36, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 16, 14, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 16, 15, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 16, 16, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 16, 17, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 17, 4, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 17, 19, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 18, 14, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 18, 15, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 18, 16, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 18, 17, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 18, 18, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 18, 19, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 19, 1, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 19, 2, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 19, 3, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 19, 4, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 19, 5, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 19, 6, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 19, 7, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 19, 8, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 19, 9, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 19, 10, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 19, 11, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 19, 12, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 19, 20, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 19, 21, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 19, 22, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 19, 23, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 19, 24, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 19, 25, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 19, 26, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 19, 27, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 19, 28, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 19, 29, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 19, 30, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 19, 31, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 19, 32, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 19, 33, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 19, 34, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 19, 35, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 20, 13, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 20, 14, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 20, 15, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 20, 16, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 20, 17, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 20, 18, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 20, 19, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 21, 4, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 21, 19, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 22, 14, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 22, 15, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 22, 16, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 22, 17, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 22, 18, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 22, 19, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 23, 26, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 23, 27, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 23, 28, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 23, 29, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 23, 30, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 23, 31, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 23, 32, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 23, 33, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 23, 34, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 23, 35, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 24, 14, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 24, 15, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 24, 16, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 24, 17, 't'),
VALUES (nextval('"ADM".res_perfiles_areas_per_dpa_con_seq'), 25, 14, 't');


